Fix comparison between pointer and integer, simplify
Instead of comparing an integer (aka char) against NULL, simply use the short form of
the ternary operator. Documented here: https://gcc.gnu.org/onlinedocs/gcc/Conditionals.html

Fixes compiler warning/error:

> ../proc_menu.c: In function 'remove_current_character_from_command_line':
> ../proc_menu.c:1847:50: error: comparison between pointer and integer