Remove calls to `min()` since I can't find it in the headers of XC16 v2.00
The compiler error is:
> ../openocd.c:215:7: error: implicit declaration of function 'min'

I suspect there _is_ a `min` function we could use for readability, but I don't see it
declared anywhere in XC16's `microchip/xc16/v2.00/include` directory